version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"

  servicea:
    container_name: servicea
    build:
      context: service-a
    environment:
      - HTTP_PORT=8080
      - CEP_SERVICE=MEMORY
      - EXPORTER_URL=http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  serviceb:
    container_name: serviceb
    build:
      context: service-b
    environment:
      - HTTP_PORT=8181
      - EXPORTER_URL=http://zipkin:9411/api/v2/spans
    ports:
      - "8181:8181"
    depends_on:
      - zipkin
