version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks: 
      - microservice
    restart: always
    ports:
      - "9411:9411"

  servicea:
    container_name: servicea
    build:
      context: service-a
    environment:
      - HTTP_PORT=8080
    networks: 
      - microservice
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  serviceb:
    container_name: serviceb
    build:
      context: service-b
    env_file:
      - .env
    networks: 
      - microservice
    environment:
      - HTTP_PORT=8181
    ports:
      - "8181:8181"
    depends_on:
      - zipkin

networks:
  microservice:
