scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: 'servicea'
    scrape_interval: 10s
    static_configs:
      - targets: ['servicea:8080']
  - job_name: 'serviceb'
    scrape_interval: 10s
    static_configs:
      - targets: ['serviceb:8181']
